version: 2
jobs:
  deploy-prod:
    docker:
      # specify the version you desire here (you might not want node)
      - image: circleci/node:10.1
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        command: sudo apt update && sudo apt install git -y && git --version
      # Update environment
      - run: sudo apt update

      # Install rsync. It will be used to upload our code to server
      - run: sudo apt-get install rsync

      # Sync the SSH keys
      - add_ssh_keys

      # Check out the code in the project directory
      - checkout
      - run: npm install express@4.15.2

      # Install JS dependencies.
      # Of course, you may not need this. It just shows how to use some commands such as npm
      - run: npm install

      # build
      - run: npm run build
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-prod:
          filters:
            branches:
              only: circleci-project-setup
